services:
  - type: web
    name: social-contract-indicators
    env: python
    rootDir: app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: DASH_DEBUG
        value: false
    plan: free
